version: 2.1

jobs:
  install:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python -m venv venv
      - run: . venv/bin/activate && pip install -r requirements.txt
      - persist_to_workspace:
          root: .
          paths:
            - venv
            - app
            - run.py
            - tests

  test:
    docker:
      - image: cimg/python:3.11
    parallelism: 2
    steps:
      - attach_workspace:
          at: .
      - run: . venv/bin/activate && pytest tests/

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - attach_workspace:
          at: .
      - run: echo "Despliegue exitoso (simulado)"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
