version: 2.1

orbs:
  slack: circleci/slack@4.12.5

jobs:
  install:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python -m venv venv
      - run: . venv/bin/activate && pip install -r requirements.txt
      - persist_to_workspace:
          root: .
          paths:
            - venv
            - app
            - run.py
            - tests

  test:
    docker:
      - image: cimg/python:3.11
    parallelism: 2
    steps:
      - attach_workspace:
          at: .
      - run: . venv/bin/activate && pytest tests/
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - attach_workspace:
          at: .
      - run: echo "Despliegue exitoso (simulado)"
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test

    # Configuración del canal de Slack
    slack/notify:
      channel: "#general"
